name: dartblog
dependencies:
  unittest: any
  crypto: any
  dart-sqlite:
#    git: git://github.com/freewind/dart-sqlite
    path: /Users/freewind/dev/github/dart-sqlite
  start: any
  hop:
    git: https://github.com/kevmoo/hop.dart.git
  petitparser:
#    git: git://github.com/freewind/PetitParserDart.git
    path: /Users/freewind/dev/github/PetitParserDart
  RythmDart:
    path: /Users/freewind/dev/workspace/RythmDart
  uuid: any
  intl: any

