name: dartblog
dependencies:
  unittest: any
  crypto: any
  dart-sqlite:
    git: https://github.com/freewind/dart-sqlite
#    path: /Users/freewind/dev/github/dart-sqlite
  start: any
  petitparser:
    git: https://github.com/freewind/PetitParserDart.git
#    path: /Users/freewind/dev/github/PetitParserDart
  RythmDart:
    git: https://github.com/freewind/RythmDart.git
#    path: /Users/freewind/dev/workspace/RythmDart
  uuid: any
  intl: any
  pathos: any
