library views;
part "src/gen/views/admin.dart";
part "src/gen/views/index.dart";
part "src/gen/views/layout.dart";
part "src/gen/views/login.dart";
part "src/gen/views/oc.dart";
part "src/gen/views/show.dart";
part "src/gen/views/topic.dart";
part "src/gen/views/writePage.dart";
