DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Config;
DROP TABLE IF EXISTS Page;
DROP TABLE IF EXISTS Category;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Link;

